"""Add lienzo_json to Proyecto

Revision ID: 00395e7daa3a
Revises: fa1ae050a900
Create Date: 2026-09-11 17:47:09.620601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00395e7daa3a'
down_revision: Union[str, Sequence[str], None] = 'fa1ae050a900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
