"""test67

Revision ID: 3568442032e6
Revises: 6f76beb78c9e
Create Date: 2026-09-12 15:15:35.453806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3568442032e6'
down_revision: Union[str, Sequence[str], None] = '6f76beb78c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagram_elements_id'), table_name='diagram_elements')
    op.drop_index(op.f('ix_diagram_elements_proyecto_id'), table_name='diagram_elements')
    op.drop_table('diagram_elements')
    op.drop_index(op.f('ix_git_objects_hash'), table_name='git_objects')
    op.drop_index(op.f('ix_git_objects_type'), table_name='git_objects')
    op.drop_table('git_objects')
    op.drop_index(op.f('ix_diagram_relations_id'), table_name='diagram_relations')
    op.drop_index(op.f('ix_diagram_relations_proyecto_id'), table_name='diagram_relations')
    op.drop_table('diagram_relations')
    op.drop_index(op.f('ix_commits_hash'), table_name='commits')
    op.drop_table('commits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tree_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_hash'], ['commits.hash'], name=op.f('commits_parent_hash_fkey')),
    sa.ForeignKeyConstraint(['tree_hash'], ['git_objects.hash'], name=op.f('commits_tree_hash_fkey')),
    sa.PrimaryKeyConstraint('hash', name=op.f('commits_pkey'))
    )
    op.create_index(op.f('ix_commits_hash'), 'commits', ['hash'], unique=False)
    op.create_table('diagram_relations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proyecto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name=op.f('diagram_relations_proyecto_id_fkey')),
    sa.ForeignKeyConstraint(['source_id'], ['diagram_elements.id'], name=op.f('diagram_relations_source_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['diagram_elements.id'], name=op.f('diagram_relations_target_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('diagram_relations_pkey'))
    )
    op.create_index(op.f('ix_diagram_relations_proyecto_id'), 'diagram_relations', ['proyecto_id'], unique=False)
    op.create_index(op.f('ix_diagram_relations_id'), 'diagram_relations', ['id'], unique=False)
    op.create_table('git_objects',
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('hash', name=op.f('git_objects_pkey'))
    )
    op.create_index(op.f('ix_git_objects_type'), 'git_objects', ['type'], unique=False)
    op.create_index(op.f('ix_git_objects_hash'), 'git_objects', ['hash'], unique=False)
    op.create_table('diagram_elements',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proyecto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pos_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pos_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name=op.f('diagram_elements_proyecto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('diagram_elements_pkey'))
    )
    op.create_index(op.f('ix_diagram_elements_proyecto_id'), 'diagram_elements', ['proyecto_id'], unique=False)
    op.create_index(op.f('ix_diagram_elements_id'), 'diagram_elements', ['id'], unique=False)
    # ### end Alembic commands ###
