"""Restaurar_tablas_proyectos

Revision ID: 6f76beb78c9e
Revises: 00395e7daa3a
Create Date: 2026-09-11 17:52:39.942017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f76beb78c9e'
down_revision: Union[str, Sequence[str], None] = '00395e7daa3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
